import { NextFunction, Request, Response } from "express";
import Question from "$models/Question.model";
import AppError from "$root/utils/AppError.util";

/**
 * @swagger
 * components:
 *   schemas:
 *     Question:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *           description: The unique identifier for the question (auto-generated by MongoDB)
 *           readOnly: true
 *         title:
 *           type: string
 *           description: The title or text of the question
 *         answers:
 *           type: array
 *           description: A list of possible answers for the question
 *           items:
 *             $ref: '#/components/schemas/Answer'
 *       required:
 *         - title
 *         - answers
 *
 *     Answer:
 *       type: object
 *       properties:
 *         title:
 *           type: string
 *           description: The text or content of the answer
 *         point:
 *           type: number
 *           description: The point value assigned to the answer
 *       required:
 *         - title
 *         - point
 */

// Get all question
/**
 * @swagger
 * /api/question:
 *   get:
 *     summary: Retrieve a list of all question
 *     tags:
 *       - Question
 *     responses:
 *       200:
 *         description: A list of question
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Question'
 *       404:
 *         description: No question found
 *       500:
 *         description: Server error
 */
const getAllQuestion = async (
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const questions = await Question.find();

    if (!questions || questions.length === 0) {
      return next(new AppError("No questions found", 404));
    }

    res.status(200).json(questions);
  } catch (err: Error | any) {
    return next(new AppError("Internal Server Error", 500));
  }
};

// Get one question
/**
 * @swagger
 * /api/question/{id}:
 *   get:
 *     summary: Retrieve a single question by ID
 *     tags:
 *       - Question
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: The question ID
 *     responses:
 *       200:
 *         description: A single question
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Question'
 *       404:
 *         description: Question not found
 *       500:
 *         description: Server error
 */
const getQuestion = async (
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const question = await Question.findById(req.params.id);

    if (!question) {
      return next(new AppError("Question not found", 404));
    }

    res.status(200).json(question);
  } catch (err: Error | any) {
    return next(new AppError("Internal Server Error", 500));
  }
};

// Create one question
/**
 * @swagger
 * /api/question:
 *   post:
 *     summary: Create a new question
 *     tags:
 *       - Question
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Question'
 *     responses:
 *       201:
 *         description: The created question
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Question'
 *       400:
 *         description: Bad request
 *       500:
 *         description: Server error
 */
const createQuestion = async (
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const { title, answers } = req.body;

    if (!title || !Array.isArray(answers) || answers.length === 0) {
      return next(new AppError("Bad request: Invalid question data", 400));
    }

    for (const ans of answers) {
      if (!ans.title || typeof ans.point !== "number") {
        return next(new AppError("Bad request: Invalid answer format", 400));
      }
    }

    const question = new Question({ title, answers });

    const newQuestion = await question.save();
    res.status(201).json(newQuestion);
  } catch (err: Error | any) {
    return next(new AppError("Internal Server Error", 500));
  }
};

// Delete one question
/**
 * @swagger
 * /api/question/{id}:
 *   delete:
 *     summary: Delete an question by ID
 *     description: This endpoint allows the deletion of an question based on its ID. Returns the deleted question if successful.
 *     tags:
 *       - Question
 *     parameters:
 *       - name: id
 *         in: path
 *         description: ID of the question to delete
 *         required: true
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Question deleted successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 _id:
 *                   type: string
 *                 message:
 *                   type: string
 *       400:
 *         description: Bad request, invalid ID format
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *       404:
 *         description: Question not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 */
const deleteQuestion = async (
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const deleteQuestion = await Question.findByIdAndDelete(req.params.id);
    if (!deleteQuestion) {
      return next(new AppError("Question not found", 404));
    }
    res.status(200).json({ message: "Delete Successfully" });
  } catch (err: Error | any) {
    return next(new AppError("Internal Server Error", 500));
  }
};

// Update one question
/**
 * @swagger
 * /api/question/{id}:
 *   put:
 *     summary: Update an question by ID
 *     description: This endpoint allows the updating of an question based on its ID. Returns the updated question if successful.
 *     tags:
 *       - Question
 *     parameters:
 *       - name: id
 *         in: path
 *         description: ID of the question to update
 *         required: true
 *         schema:
 *           type: string
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Question'
 *     responses:
 *       200:
 *         description: Question after updated
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Question'
 *       404:
 *         description: Question not found
 *       500:
 *         description: Server error
 */
const updateQuestion = async (
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const updatedQuestion = await Question.findByIdAndUpdate(
      req.params.id,
      req.body,
      {
        new: true,
      }
    );
    if (!updatedQuestion) {
      return next(new AppError("Question not found", 404));
    }
    res
      .status(200)
      .json({ message: "Question updated successfully", updatedQuestion });
  } catch (err: Error | any) {
    res.status(500).json({ message: err.message });
    return next(new AppError("Internal Server Error", 500));
  }
};

const QuestionAPI = {
  getQuestion,
  getAllQuestion,
  createQuestion,
  deleteQuestion,
  updateQuestion,
};
export default QuestionAPI;
